importpandasaspd
importtime
fromfintaimport TA
import numpy as np
import pandas as pd
import datetime as dt
import copy
import json
from py5paisa import FivePaisaClient

client = FivePaisaClient(email="sudhanshu8833@gmail.com", passwd="Madhya246###", dob="20010626")
client.login()




def candle(instrument):
    df=client.historical_data('N','C',instrument,'1d','2021-04-29','2021-06-26')
    df['volume average']=df['Volume'].rolling(30).mean()
    # print(df)
    return df


df=pd.read_csv(r'scripmaster-csv-format.csv')

scripcode=[]
symbol=[]

for i in range(len(df)):
    if df['Exch'][i]=='N' and df["ExchType"][i]=='C' and df["Series"][i] == 'EQ':
        scripcode.append(df['Scripcode'][i])
        symbol.append(df['Name'][i])

ohlc_dict=pd.DataFrame()
ohlc_dict['scripcode']=np.array(scripcode)
ohlc_dict['symbol']=np.array(symbol)
ohlc_opg=pd.DataFrame()
# print(ohlc_dict)
symbol1=[]
scripcode1=[]
stocks=[]
k=1
for i in range(len(ohlc_dict)):
    try:
        print("sahi hai",i)
        df=candle(int(ohlc_dict['scripcode'][i]))
        if df['volume average'].iloc[-1]>50000 and df['Close'].iloc[-1]>40 and df['Close'].iloc[-1]<1000:
            symbol1.append(ohlc_dict['symbol'][i])
            # scripcode1.append(ohlc_dict['scripcode'][i])
    except:
        print("moving aage: ",k)
        k+=1
        # stocks.append(ohlc_dict['symbol'])
# ohlc_opg['scripcode1']=np.array(scripcode1)
# ohlc_opg['symbol1']=np.array(symbol1)

print(symbol1)



['AARTIIND','ABAN','ALEMBICLTD','AMARAJABAT','SHAREINDIA','ANDHRSUGAR','GODREJAGRO','APCOTEXIND','APOLLOTYRE','ANDHRAPAP','ARVIND','UNIDT','ASHOKLEY','IEX','AAKASH','CHEMCON','AUROPHARMA','GICRE','ANGELBRKG','BALMLAWRIE','BALRAMCHIN','BANARBEADS','NAM-INDIA','BEL','MAHLOG','NIACL','BERGEPAINT','BEPL','BHARATFORG','KHADIM','BHARATGEAR','IFGLEXPOR','BHEL','5PAISA','TATASTLBSL','HDFCLIFE','BIRLACABLE','MAZDOCK','BOMDYEING','BPCL','UTIAMC','RELINFRA','BSL','LIKHITHA','CANFINHOME','GRAPHITE','CARBORUNIV','CENTENKA','CENTURYTEX','CESC','IGARASHI','CHAMBLFERT','EXIDEIND','CHOLAFIN','CIPLA','HEMIPROP','SHALBY','CLNINDIA','TATACOFFEE','COROMANDEL','COSMOFILMS','FSC','DABUR','DALMIASUG','DCM','DCMSHRIRAM','DCW','DEEPAKFERT','DHAMPURSUG','ASTRON','KHAICHEM','EQUITASBNK','EIDPARRY','EIHOTEL','ELGIEQUIP','SUBEXLTD','EPL','EVERESTIND','FACT','FEDERALBNK','FINCABLES','FINPIPE','UFLEX','ZENSARTECH','GABRIEL','GHCL','APOLLO','GICHSGFIN','GIPCL','NEWGEN','GMBREW','GNFC','FMGOETZE','KANSAINER','GREAVESCOT','GSFC','CASTROLIND','GUJALKALI','AMBUJACEM','GFLLIMITED','HARRMALAYA','MARINE','HIMATSEIDE','HINDALCO','HINDOILEXP','HINDPETRO','HSIL','HINDZINC','REPL','IFBAGRO','BURGERKING','SHIVAMILLS','ASTERDM','INDHOTEL','INDIACEM','INDIAGLYCO','INDIANHUME','RKEC','MGEL','INGERRAND','IOC','BECTORFOOD','ITC','HGINFRA','ITI','JAYBARMARU','JAYSREETEA','JINDALPOLY','KANPRPLA','AWHCL','KABRAEXTRU','KAJARIACER','KAKATCEM','KALPATPOWR','KANORICHEM','KARURVYSYA','KCP','KESORAMIND','ACRYSIL','CUMMINSIND','KOPRAN','KSB','TRENT','LIBERTSHOE','LICHSGFIN','AHLADA','M&M','CHENNPETRO','HOMEFIRST','MAHSEAMLES','MANGLMCEM','STOVEKRAFT','BDL','SUNDARMHLD','MOREPENLAB','BANDHANBNK','MRPL','BESTAGRO','MUNJALSHOW','HEIDELBERG','NCC','SMCGLOBAL','NAVNETEDUL','NELCO','SANDHAR','RAILTEL','NOCIL','CENTRUM','MIDHANI','ONGC','ISEC','SILGO','BCLIND','HUHTAMAKI','LEMONTREE','HERANBA','PHILIPCARB','PRAKASH','PRECWIRE','PRSMJOHNSN','JUBLINGREA','EASEMYTRIP','RSWM','RALLIS','ANURAS','LXCHEM','RANEHOLDIN','RAYMOND','RCF','HITECH','RICOAUTO','RIIL','RUBYMILLS','KALYANKJIL','SAIL','SURYODAY','ORIENTELEC','SANGHIIND','WONDERLA','NETFSDL26','JINDALSAW','SBIN','SCI','VEDL','SESHAPAPER','SHANTIGEAR','INDOSTAR','SHREDIGCEM','SHREYANIND','BARBEQUE','SHREYAS','SIMPLEXINF','LODHA','JTEKTINDIA','SPIC','TEMBO','STARPAPER','DEEPINDS','SURYAROSNI','SMLISUZU','AGARIND','TATACHEM','TATAPOWER','TATACONSUM','TATAMOTORS','TFCILTD','THOMASCOOK','TINPLATE','TIRUMALCHM','TNPETRO','UCALFUEL','UNICHEMLAB','UNIVCABLES','JUBLPHARMA','VIPIND','VLSFINANCE','WALCHANNAG','WATERBASE','RITES','WHEELS','WIPRO','WSTCSTPAPR','ZEEL','ZODIACLOTH','ZUARIGLOB','TOKYOPLAST','VARROC','SOMANYCERA','HATSUN','CAPLIPOINT','PREMIERPOL','GOCLCORP','TNPL','GREENPLY','CORALFINAC','NBVENTURES','AUSOMENT','JAYAGROGN','PANACEABIO','MARICO','TCNSBRANDS','MOTHERSUMI','VISAKAIND','DENORA','STERTOOLS','GULFOILLUB','MIRZAINT','JAGSNPHARM','CREDITACC','JMCPROJECT','HITECHGEAR','ELECTHERM','AARTIDRUGS','SIGIND','RAMCOIND','KOTHARIPET','HERITGFOOD','BANKBARODA','GAIL','SKMEGGPROD','BANKINDIA','INDNIPPON','CONCOR','INDRAMEDCO','SNOWMAN','INDSWFTLAB','FDC','ENGINERSIN','ICICIBANK','IRCON','SHARDACROP','CIGNITITEC','JAICORPLTD','GMDCLTD','ASAHIINDIA','TRIGYN','GRSE','KOTHARIPRO','ITDCEM','CUB','CYIENT','KOTAKBKETF','AXISBANK','INTELLECT','MONTECARLO','CYBERTECH','GOODLUCK','FCL','CAMLINFINE','DTIL','GULPOLY','MAN50ETF','NATIONALUM','LAMBODHARA','RSSOFTWARE','TECHNOE','SONATSOFTW','MOLDTKPAC','JINDALSTEL','MENONBE','BSOFT','JMA','HCLTECH','SETFNIFBK','STAR','RAJESHEXPO','GLENMARK','WOCKPHARMA','ZENTEC','TREJHARA','NRBBEARING','RAMCOSYS','INOXWIND','GEPIL','CADILAHC','AVANTIFEED','MAHLIFE','KTKBANK','RPSGVENT','SPENCERS','BLUESTARCO','XELPMOC','TVSMOTOR','NETFMID150','CHALET','NLCINDIA','VETO','VRLLOG','PNBGILTS','GAEL','USHAMART','NOVARTIND','ANUP','UFO','ARVINDFASN','BALAJITELE','STLTECH','TAJGVK','MSTCLTD','PNCINFRA','SKIPPER','AXISCADES','SAKAR','MAHESHWARI','HIKAL','KPITTECH','SMARTLINK','NEOGEN','EMAMIPAP','GODREJCP','SETFNIF50','CONFIPET','SYNGENE','KAYA','AYMSYNTEX','PPL','RAMASTEEL','MAJESCO','STEELCITY','MUTHOOTCAP','MCDOWELL-N','SATIN','ARVSMART','POWERMECH','SHARDAMOTR','NAVKARCORP','NIFTYBEES','KRBL','MARKSANS','TCI','SHREEPUSHK','GUJGASLTD','BHARTIARTL','OLECTRA','PONNIERODE','PNB','OMAXAUTO','GODREJIND','JUNIORBEES','STCINDIA','RADICO','INFOBEAN','ICICIBANKN','DCMNVL','SATIA','SIRCA','SECURKLOUD','NATHBIOGEN','LIBAS','CREATIVE','IDFCFIRSTB','SHK','VARDHACRLC','SUVEN','JSL','WELSPUNIND','JAIBALAJI','IGL','TVSELECT','DREDGECORP','TVTODAY','UPL','UNIENTER','PETRONET','PTC','VAIBHAVGBL','TTKHLTCARE','BIOCON','UMANGDAIRY','ZOTA','SALZERELEC','RKFORGE','DATAMATICS','NDTV','SPANDANA','BANKBEES','SPICEJET','CCL','APARINDS','NIITLTD','TEXINFRA','WESTLIFE','GULFPETRO','LINCOLN','GUFICBIO','ASTRAMICRO','WELENT','NTPC','KOTARISUG','JBMA','DWARKESH','INDOCO','SUPRAJIT','XCHANGING','JSWSTEEL','GDL','VISHAL','GOKEX','EVEREADY','SHOPERSTOP','MANGALAM','WELCORP','NH','JKPAPER','GRANULES','MANINDS','GEOJITFSL','GENUSPOWER','NECLIFE','SPLIL','IDFC','GOLDIAM','RML','ICIL','AURIONPRO','DOLAT','JSLHISAR','SWSOLAR','PRECAM','IIFLSEC','SORILINFRA','TRIVENI','VIMTALABS','NAHARINDUS','QUICKHEAL','NITINSPIN','ROHLTD','ENIL','GSPL','JAGRAN','INOXLEISUR','SADBHAV','KEC','INDOTECH','M&MFIN','CENTURYPLY','KEI','GALLANTT','VAKRANGEE','UTTAMSUGAR','BHAGERIA','SUNTV','RSYSTEMS','EMKAY','KELLTONTEC','KAMDHENU','PIONEEREMB','JKLAKSHMI','ALLCARGO','MUNJALAU','EMAMILTD','VIDHIING','ACE','SELAN','JMFINANCIL','ELECON','TALBROAUTO','GEECEE','GATI','VISHWARAJ','FIEMIND','DCBBANK','INSPIRISYS','GESHIP','TORNTPOWER','SUTLEJTEX','DAAWAT','RUCHIRA','SOBHA','DONEAR','VENUSREM','KUANTUM','JINDRILL','BANCOINDIA','HIRECT','CREST','PLASTIBLEN','NFL','HBLPOWER','JASH','AVTNPL','LUMAXTECH','SANGHVIMOV','IGPL','SIYSIL','PTL','AUTOIND','NETWORK18','GANDHITUBE','PITTIENG','MINDAIND','IZMO','TV18BRDCST','TIIL','REDINGTON','ORIENTBELL','SEQUENT','PFC','FSL','INDIANB','SMSPHARMA','HSCL','GANESHHOUC','LAOPALA','GOLDBEES','JKTYRE','NAHARSPING','NAHARPOLY','IBREALEST','KIRLFER','GOKULAGRO','THEMISMED','NCLIND','BANSWRAS','GOLDSHARE','PHOENIXLTD','AROGRANITE','BFUTILITIE','SRHHYPOLTD','FORTIS','ALPHAGEO','WEBELSOLAR','CHEMBOND','INSECTICID','MCDHOLDING','GUJAPOLLO','GOACARBON','TIMETECHNO','DLF','NELCAST','V2RETAIL','TARMAT','SPARC','ADSL','DECCANCE','OMAXE','ASIANTILES','TAKE','PURVA','SRIPIPES','MAHINDCIE','MOTILALOFS','CSBBANK','KSCL','POWERGRID','MANGCHEFER','MAANALU','DELTACORP','RELIGARE','ADANIPORTS','EDELWEISS','KOLTEPATIL','RGL','JYOTHYLAB','MADHAV','HITECHCORP','BRIGADE','BGRENERGY','MANAKSIA','ARIES','PPAP','DVL','BIRLAMONEY','JKIL','CORDSCABLE','ONMOBILE','KNRCON','HERCULES','IRB','NMDC','RAIN','SHALPAINTS','GSS','RECLTD','NAHARCAP','VGUARD','DHANI','EIHAHOTELS','NESCO','TWL','HCG','PRINCEPIPE','BHARATWIRE','INFIBEAM','PANACHE','MMP','VAISHALI','KIRIINDUS','RPGLIFE','GET&D','VINYLINDIA','KOKUYOCMLN','EQUITAS','DPWIRES','20MICRONS','JOCIL','ALKALI','TATAMTRDVR','MAWANASUG','HINDNATGLS','UJJIVAN','CROMPTON','SUMICHEM','PARAGMILK','ALBERTDAVD','BLS','AJMERA','MHRIL','AMRUTANJAN','ASALCBR','MAHEPC','MOLDTECH','SUNTECK','POKARNA','GPTINFRA','QUESS','DEN','SHILPAMED','SARDAEN','REFEX','DLINKINDIA','JSWENERGY','DBCORP','HINDCOPPER','SUVENPHAR','MMTC','SBICARD','TRF','ADVENZYMES','MINDTECK','DBL','KOTAKNIFTY','THANGAMAYL','EMMBI','TEXMOPIPES','MANINFRA','DEEPENR','SPAL','LGBBROSLTD','FRETAIL','RBLBANK','ASIANHOTNR','ISFT','CUPID','GNA','ICICIPRULI','MARATHON','HPL','VERTOZ','KSL','PNBHOUSING','VBL','PIONDIST','MANAPPURAM','AARVI','KIOCL','CMICABLES','HMVL','LAURUSLABS','IMFA','BLISSGVS','DFMFOODS','EMAMIREAL','TERASOFT','ITDC','HISARMETAL','BOROLTD','BAJAJCON','HDFCMFGETF','BSE','PRICOLLTD','ICICIGOLD','GPPL','SASTASUNDR','INTENTECH','CAREERP','RAMKY','GALLISPAT','CANTABIL','AKSHARCHEM','ASHOKA','WABAG','CLEDUCATE','OBEROIRLTY','PRESTIGE','NRAIL','SHANKARA','RESPONIND','CGCL','COALINDIA','IOLCP','NACLIND','APCL','AXISGOLD','GRAVITA','DOLLAR','SUPERHOUSE','JINDWORLD','SCHAND','RPPINFRA','BHAGYANGR','JAMNAAUTO','HUDCO','MOIL','PSPPROJECT','KIRLOSENG','STARCEMENT','BFINVEST','ERIS','CDSL','GTPL','ICICILOVOL','DYNPRO','STEELXIND','SALASAR','MAGADSUGAR','AVADHSUGAR','STEL','SIS','COCHINSHIP','JUBLINDS','SMSLIFE','ABCAPITAL','APEX','DCAL','LASA','CHOLAHLDNG','CAPACITE','DIAMONDYD','HFCL','INDTERRAIN','WORTH','MACPOWER','ICICITECH','MAXHEALTH','TOTAL','MAXIND','N100','ESTER','ASHIANA','DHANUKA','FILATEX','L&TFH','BODALCHEM','BROOKS','TDPOWERSYS','APLLTD','PGEL','PANAMAPET','PAISALO','SHAKTIPUMP','TRITURBINE','DSSL','POLYMED','RUPA','MINDACORP','TBZ','VSSL','SWANENERGY','SPECIALITY','CINELINE','KITEX','MAYURUNIQ','ROSSELLIND','ZUARI','CARERATING','INDUSTOWER','ICICINIFTY','REPCOHOME','GSCLCEMENT','ORIENTREF','SCHNEIDER','NBCC','APTECHT','NUCLEUS','CANBK','SEYAIND','ADANIPOWER','GLOBUSSPR','OIL','MAXVIL','CONTROLPR','EXPLEOSOL','MAHASTEEL','ADORWELD','AEGISCHEM','HAPPSTMNDS','MODISNME','SUBROS','SUDARSCHEM','ISGEC','SUNDRMFAST','SUNFLAG','SUNPHARMA','JUSTDIAL','CEREBRAINT','ATULAUTO','ORIENTCEM','ABFRL','IBULHSGFIN','FLFL']