# Generated by Django 5.0.1 on 2024-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0007_positions_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='SOME STRING', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='strategy',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='open_position',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='strategy_id',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='strategy_id',
        ),
    ]
