# Generated by Django 5.0.1 on 2024-01-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0008_admin_delete_strategy_delete_user1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='positions',
        ),
    ]
