# Generated by Django 5.0.1 on 2024-01-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0009_delete_orders_delete_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
