# Generated by Django 2.2.1 on 2020-06-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0002_bot_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='data_size',
        ),
        migrations.AddField(
            model_name='bot',
            name='cash_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='margin_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
