# Generated by Django 2.2.1 on 2020-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0004_auto_20200611_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='order_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
