# Generated by Django 2.2.1 on 2020-06-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0007_auto_20200617_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 19, 24, 14, 246320)),
        ),
    ]
