# Generated by Django 2.2.1 on 2020-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0008_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
