# Generated by Django 2.2.1 on 2021-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0011_auto_20210429_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='parameter',
        ),
        migrations.AddField(
            model_name='strategy',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='part',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
