# Generated by Django 2.2.1 on 2021-04-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0014_auto_20210430_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
