# Generated by Django 2.2.1 on 2021-04-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0015_bot_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='close_long',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='close_short',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='entry_long',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='entry_short',
        ),
        migrations.AddField(
            model_name='bot',
            name='close',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='side',
            field=models.CharField(default='Call', max_length=20),
        ),
    ]
