# Generated by Django 4.0.6 on 2022-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0007_positions_current_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='lot',
            new_name='lots',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='strategy_id',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='ET',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='LIMIT',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T3',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T4',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T5',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='TP1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='TP2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='T_now',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='buy_factor',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='expiry_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='expiry_2',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='expiry_selected',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='percentage_premium',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sell_factor',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='strategy_id',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='v_factor',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='working_days_1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='working_days_2',
        ),
        migrations.AddField(
            model_name='strategy',
            name='angel_api_keys',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='strategy',
            name='angel_client_id',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='angel_password',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='bot',
            field=models.CharField(default='on', max_length=4),
        ),
        migrations.AddField(
            model_name='strategy',
            name='monthly_expiry',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='paper',
            field=models.CharField(default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='strategy',
            name='username',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='weekly_expiry',
            field=models.CharField(default='NONE', max_length=10),
        ),
    ]
