# Generated by Django 4.0.6 on 2022-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0009_alter_positions_id_alter_strategy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='bots_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
