# Generated by Django 4.0.6 on 2022-09-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0010_strategy_bots_started_alter_positions_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='pnl',
            field=models.FloatField(default=0),
        ),
    ]
