# Generated by Django 4.0.6 on 2022-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0011_positions_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='angel_token',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='angel_password',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
