# Generated by Django 4.0.6 on 2022-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0012_strategy_angel_token_alter_strategy_angel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='shift_position',
            field=models.CharField(default='on', max_length=10),
        ),
    ]
