# Generated by Django 2.2.1 on 2020-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('sure_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.IntegerField(default=2)),
                ('td_refresh_token', models.TextField()),
                ('td_consumer_key', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.TextField()),
                ('close_time', models.TimeField()),
                ('data_size', models.IntegerField(default=250)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=1)),
                ('indicator', models.CharField(max_length=100)),
                ('parameter', models.TextField()),
            ],
        ),
    ]
