# Generated by Django 2.2.1 on 2020-06-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='strategy',
            field=models.IntegerField(default=1),
        ),
    ]
