# Generated by Django 2.2.1 on 2020-06-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0003_auto_20200608_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='time_frame',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bot',
            name='type',
            field=models.CharField(default='paper', max_length=20),
        ),
    ]
