# Generated by Django 2.2.1 on 2020-06-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='position',
            field=models.FloatField(default=0),
        ),
    ]
