# Generated by Django 2.2.1 on 2021-04-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='td_consumer_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='td_refresh_token',
            field=models.TextField(default=''),
        ),
    ]
