# Generated by Django 2.2.1 on 2021-04-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0013_auto_20210429_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='margin_amount',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='close_long',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='close_short',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='entry_long',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='entry_short',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_owner', to='Trading.User'),
        ),
    ]
